### ISSUE TITLE
Dead Link in SCF Docs

### ISSUE THREAD

**Issue by JacksonBurns** [pyscf/pyscf.github.io#125]
Hello!

This page: https://pyscf.org/user/scf.html#property-calculations

says: `see the examples in examples/prop/17-stability.py`

which links to: https://github.com/pyscf/pyscf/tree/master/examples/prop/17-stability.py

that does not exist any more at that link. Should it be pointing to something here: https://github.com/pyscf/pyscf.github.io/blob/master/examples/prop/01-freq.py ?

**Comment by matthew-hennefarth** [comment]
Has this issue been fixed? If so, we should close the issue.
