### ISSUE TITLE
Problem /error in "How to use pyscf"

### ISSUE THREAD

**Issue by steto123** [pyscf/pyscf.github.io#139]
I have a problem with an example in this chapter:

The given example is

from pyscf import gto, scf, ccsd

mol = gto.M(atom='H 0 0 0; H 0 0 1.1', basis='ccpvtz')
mf = scf.RHF(mol).run()
mycc = ccsd.CCSD(mf).run()
print(mycc.e_tot)
print(mycc.e_corr)
print(mycc.t1.shape)
print(mycc.t2.shape)

and the error is 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[4], line 1
----> 1 from pyscf import gto, scf, ccsd
      3 mol = gto.M(atom='H 0 0 0; H 0 0 1.1', basis='ccpvtz')
      4 mf = scf.RHF(mol).run()

ImportError: cannot import name 'ccsd' from 'pyscf' (/home/#####/.conda/envs/myjupyter/lib/python3.10/site-packages/pyscf/__init__.py)

-------------------------------------------------------------------------------------------------------
What is the problem? Is there no module named ccsd?

Any help is very welcome

**Comment by tberkel** [comment]
Sorry, it should be `from pyscf import cc`. I'll fix it on the website.
