### ISSUE TITLE
mol.natm is zero

### ISSUE THREAD

**Issue by steto123** [pyscf/pyscf.github.io#145]
i am willing to learn the usage of pyscf, but it is really frustrating.

Today i read https://pyscf.org/user/gto.html

and there is a example for definig geometry using a script

from pyscf import gto
mol = gto.Mole()
mol.atom = [['O',(0, 0, 0)], ['H',(0, 1, 0)], ['H',(0, 0, 1)]]
mol.atom.extend([['H', (i, i, i)] for i in range(1,5)])

My attempt to visualize the resulting molecule using rdkit failed. Now i add mol.natm and the end of this snippet and surprisingly it is zero. I insert mol.build bevor mol.natm and no changes in the atom number is detected. Now i know the reason for failing the visulasation but i do not understand: why mol.atom is zero. 
I also comment the line with mol.atom.extend. and mol.natm is also zero!

What is my fault?

**Comment by tberkel** [comment]
As described on that page, `mol.build()` is a function, so it needs parentheses.
```
from pyscf import gto
mol = gto.Mole()
mol.atom = [['O',(0, 0, 0)], ['H',(0, 1, 0)], ['H',(0, 0, 1)]]
mol.atom.extend([['H', (i, i, i)] for i in range(1,5)])
mol.build()
print(mol.natm)
# 7
```
In the future, questions like this should be raised as issues on the github for the pyscf package (`pyscf/pyscf`), not the github for the website (`pyscf/pyscf.github.io`).

**Comment by steto123** [comment]
Many thanks for your answer.
I think this is also a problem with the documentation.  The examples given are very short.

**Comment by tberkel** [comment]
Thanks, we'll keep that in mind. If you haven't already, I suggest reading the [How to use PySCF](https://pyscf.org/user/using.html) section of the documentation, which describes PySCF's organization into modules, classes, and methods, and to also look at the large set of [examples](https://github.com/pyscf/pyscf/tree/master/examples) in the PySCF distribution.
