### ISSUE TITLE
Installing requirement sphinx_rtd_theme

### ISSUE THREAD

**Issue by verena-neufeld** [pyscf/pyscf.github.io#27]
I believe sphinx_rtd_theme is also needed as a prerequisite unless I have been doing things wrong?

**Comment by fishjojo** [comment]
Yes, you are right

**Comment by tberkel** [comment]
For whatever it's worth, the requirements to build the docs are going to
change a bit when we merge the docs and the website

**Comment by verena-neufeld** [comment]
I have no preference, we can review it then if you like.

**Comment by verena-neufeld** [comment]
I am closing it since the requirements will change.
