### ISSUE TITLE
Example 43-AVAS does not finish running

### ISSUE THREAD

**Issue by PabloAMC** [pyscf/pyscf.github.io#29]
I have been trying the AVAS example, but before being able to do anything about it, there is an issue with a self-consistent calculation. Line:
https://github.com/pyscf/pyscf-doc/blob/93f34be682adf516a692e28787c19f10cbb4b969/examples/mcscf/43-avas.py#L49
is not able to finish execution.
I have tried it both in my personal laptop for larger times than an hour, and in google colab for more than half an hour and it never finishes. I am inclined to think there might be an issue.
(Installation was done in both cases via `pip install pyscf`)

**Comment by fishjojo** [comment]
This example should run. You may try setting `mol.verbose=5` to see more information. You would expect a few (> 3) hours to finish running this example with single core CPU.

**Comment by susilehtola** [comment]
It might be useful to add a comment to the example saying it will take a long time to run..

**Comment by PabloAMC** [comment]
Yeah, you're right that it works. Just for very long times
