### ISSUE TITLE
for loops

### ISSUE THREAD

**Issue by IsabelRunne** [pyscf/pyscf.github.io#3]
Can anyone assist me with writing for loops in pyscf?

**Comment by gkc1000** [comment]
Sorry, not here! Perhaps try

reddit.com/r/learnpython

**Comment by IsabelRunne** [comment]
<img width="1440" alt="Screen Shot 2021-02-24 at 11 01 05 PM" src="https://user-images.githubusercontent.com/77126001/109105803-3e0bf180-76f4-11eb-8893-75185c3bc98b.png">

I cannot figure out how to use f strings or dot formatting to use the variable " i " in my for loop

**Comment by gkc1000** [comment]
It looks like you are making a molecule with a bond length of 0, which
would be a problem.

**Comment by IsabelRunne** [comment]
Thank you
