### ISSUE TITLE
band structure from HF and hybrids

### ISSUE THREAD

**Issue by gkc1000** [pyscf/pyscf.github.io#67]
A perennial question is how to use get_bands with HF. One should either
(i) shift the BZ mesh or
(ii) use exxdiv="vcut_sph" (or "ws?")
This should be documented since this comes up from time to time.

**Comment by tberkel** [comment]
I already documented this here:
https://pyscf.org/user/pbc/scf.html#band-structure-calculations

**Comment by gkc1000** [comment]
Oh great! Lin was asking. Closing issue.
