### ISSUE TITLE
Add examples using XYZ files to initialize a geometry in User Guide

### ISSUE THREAD

**Issue by jamesETsmith** [pyscf/pyscf.github.io#72]
## Problem
Currently `source/user/gto.rst` doesn't have any examples showing how to initialize a molecule using an XYZ file.

## Solution

Add another example, something along the lines of:

```python
mol = gto.M(atom="coronene.xyz", basis="ccpvtz", verbose=5)
```

**Comment by susilehtola** [comment]
Great idea, file a pull and I'll merge it

**Comment by jamesETsmith** [comment]
Will do, I'm a bit busy today, but I'll try to do it in the next day or two
