### ISSUE TITLE
Replace hard-coded examples in the docs with includes

### ISSUE THREAD

**Issue by susilehtola** [pyscf/pyscf.github.io#9]
The manual has several examples hard-coded in its source. This is suboptimal, since running the examples then requires copypasting the code to a Python terminal. A better solution would be to replace the hard-coded examples by include statements; that way users can run the examples without copy-paste.

**Comment by verena-neufeld** [comment]
Would it make sense to somehow combine this partly with the pyscf examples? Will those examples be unit tested regularly in case they become outdated?

**Comment by susilehtola** [comment]
Yes, that's what I mean: the manual should include the examples verbatim from the PySCF source tree.

I don't know if the examples are unit tested.

**Comment by susilehtola** [comment]
We're also missing examples for many functionalities, e.g. magnetizabilities are missing even though examples exist within the unit tests.

**Comment by susilehtola** [comment]
I guess we came to the conclusion that we don't want to do this
